### ISSUE TITLE
Unable to display 4K video correctly

### ISSUE THREAD

**Issue by TingtingG233** [jeremyVignelles/libvlcsharp-nonfree-samples#1]
Hi，I know my question has no reletion with this project ,but I found you appear from [ZeBobo5](https://github.com/ZeBobo5)
/
[Vlc.DotNet](https://github.com/ZeBobo5/Vlc.DotNet) so I was trying to ask for your kindly help here.

I was trying to display 4K video use VLCControl，but when I select the lower resolution video it works but when I try to display 4K video the view seems like it is squeezed.  And the screen the video screen looks like a strip. I thinks maybe I should add some VlcMediaplayerOptions  but I don't know where to check the whole options and which one will work.
Can you please help me ?
Best regards,
Tingting

![1665306782026](https://user-images.githubusercontent.com/84501789/194748359-42fe1e29-1aec-4b27-98ad-a3d30493b120.png)

**Comment by jeremyVignelles** [comment]
This is not the correct place to do that. There is a discord, where people sometimes help on their free time, and a stackoverflow.
Also, Vlc.DotNet is deprecated, and that likely would require a fix in the code. What if you tried switching to LibVLCSharp ? What if you tried embedding the WinForms control in the WindowsFormsHost to allow better performance ?

Closing this as I won't help here anymore. Good luck.
